# Generated by Django 2.2 on 2019-11-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20191123_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercoursesectionsign',
            options={'verbose_name': '用户课程段落标记', 'verbose_name_plural': '用户课程段落标记'},
        ),
    ]
