# Generated by Django 2.2 on 2019-12-11 13:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_knowledge_point'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0004_auto_20191204_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCoursePointSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('sign', models.BooleanField(verbose_name='1代表认为困难')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='标记的课程')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Knowledge_point', verbose_name='标记的知识点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户课程知识点标记',
                'verbose_name_plural': '用户课程知识点标记',
            },
        ),
    ]
