# Generated by Django 2.2 on 2019-12-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_usercoursepointsign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoursepointsign',
            name='sign',
        ),
    ]
