# Generated by Django 2.2 on 2019-12-11 12:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20191123_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=100, verbose_name='知识点')),
                ('sign_num', models.IntegerField(default=0, verbose_name='用户标记数')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程名')),
            ],
            options={
                'verbose_name': '知识点信息',
                'verbose_name_plural': '知识点信息',
                'unique_together': {('course', 'name')},
            },
        ),
    ]
