# Generated by Django 2.2 on 2019-12-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191204_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='head_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='地址'),
        ),
    ]
